// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v3.5.0
// source: imbotclients/pbdefines/chatroom.proto

package pbobjs

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChrmEventType int32

const (
	ChrmEventType_Join    ChrmEventType = 0
	ChrmEventType_Quit    ChrmEventType = 1
	ChrmEventType_Kick    ChrmEventType = 2
	ChrmEventType_Fallout ChrmEventType = 3
)

// Enum value maps for ChrmEventType.
var (
	ChrmEventType_name = map[int32]string{
		0: "Join",
		1: "Quit",
		2: "Kick",
		3: "Fallout",
	}
	ChrmEventType_value = map[string]int32{
		"Join":    0,
		"Quit":    1,
		"Kick":    2,
		"Fallout": 3,
	}
)

func (x ChrmEventType) Enum() *ChrmEventType {
	p := new(ChrmEventType)
	*p = x
	return p
}

func (x ChrmEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChrmEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_imbotclients_pbdefines_chatroom_proto_enumTypes[0].Descriptor()
}

func (ChrmEventType) Type() protoreflect.EnumType {
	return &file_imbotclients_pbdefines_chatroom_proto_enumTypes[0]
}

func (x ChrmEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChrmEventType.Descriptor instead.
func (ChrmEventType) EnumDescriptor() ([]byte, []int) {
	return file_imbotclients_pbdefines_chatroom_proto_rawDescGZIP(), []int{0}
}

type ChrmDispatchType int32

const (
	ChrmDispatchType_CreateChatroom  ChrmDispatchType = 0
	ChrmDispatchType_DestroyChatroom ChrmDispatchType = 1
)

// Enum value maps for ChrmDispatchType.
var (
	ChrmDispatchType_name = map[int32]string{
		0: "CreateChatroom",
		1: "DestroyChatroom",
	}
	ChrmDispatchType_value = map[string]int32{
		"CreateChatroom":  0,
		"DestroyChatroom": 1,
	}
)

func (x ChrmDispatchType) Enum() *ChrmDispatchType {
	p := new(ChrmDispatchType)
	*p = x
	return p
}

func (x ChrmDispatchType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChrmDispatchType) Descriptor() protoreflect.EnumDescriptor {
	return file_imbotclients_pbdefines_chatroom_proto_enumTypes[1].Descriptor()
}

func (ChrmDispatchType) Type() protoreflect.EnumType {
	return &file_imbotclients_pbdefines_chatroom_proto_enumTypes[1]
}

func (x ChrmDispatchType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChrmDispatchType.Descriptor instead.
func (ChrmDispatchType) EnumDescriptor() ([]byte, []int) {
	return file_imbotclients_pbdefines_chatroom_proto_rawDescGZIP(), []int{1}
}

type ChatMembersDispatchType int32

const (
	ChatMembersDispatchType_DispatchDefault ChatMembersDispatchType = 0
	ChatMembersDispatchType_JoinChatroom    ChatMembersDispatchType = 1
	ChatMembersDispatchType_QuitChatroom    ChatMembersDispatchType = 2
)

// Enum value maps for ChatMembersDispatchType.
var (
	ChatMembersDispatchType_name = map[int32]string{
		0: "DispatchDefault",
		1: "JoinChatroom",
		2: "QuitChatroom",
	}
	ChatMembersDispatchType_value = map[string]int32{
		"DispatchDefault": 0,
		"JoinChatroom":    1,
		"QuitChatroom":    2,
	}
)

func (x ChatMembersDispatchType) Enum() *ChatMembersDispatchType {
	p := new(ChatMembersDispatchType)
	*p = x
	return p
}

func (x ChatMembersDispatchType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChatMembersDispatchType) Descriptor() protoreflect.EnumDescriptor {
	return file_imbotclients_pbdefines_chatroom_proto_enumTypes[2].Descriptor()
}

func (ChatMembersDispatchType) Type() protoreflect.EnumType {
	return &file_imbotclients_pbdefines_chatroom_proto_enumTypes[2]
}

func (x ChatMembersDispatchType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChatMembersDispatchType.Descriptor instead.
func (ChatMembersDispatchType) EnumDescriptor() ([]byte, []int) {
	return file_imbotclients_pbdefines_chatroom_proto_rawDescGZIP(), []int{2}
}

type ChatAttOptType int32

const (
	ChatAttOptType_ChatAttOpt_Default ChatAttOptType = 0
	ChatAttOptType_ChatAttOpt_Add     ChatAttOptType = 1
	ChatAttOptType_ChatAttOpt_Del     ChatAttOptType = 2
)

// Enum value maps for ChatAttOptType.
var (
	ChatAttOptType_name = map[int32]string{
		0: "ChatAttOpt_Default",
		1: "ChatAttOpt_Add",
		2: "ChatAttOpt_Del",
	}
	ChatAttOptType_value = map[string]int32{
		"ChatAttOpt_Default": 0,
		"ChatAttOpt_Add":     1,
		"ChatAttOpt_Del":     2,
	}
)

func (x ChatAttOptType) Enum() *ChatAttOptType {
	p := new(ChatAttOptType)
	*p = x
	return p
}

func (x ChatAttOptType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChatAttOptType) Descriptor() protoreflect.EnumDescriptor {
	return file_imbotclients_pbdefines_chatroom_proto_enumTypes[3].Descriptor()
}

func (ChatAttOptType) Type() protoreflect.EnumType {
	return &file_imbotclients_pbdefines_chatroom_proto_enumTypes[3]
}

func (x ChatAttOptType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChatAttOptType.Descriptor instead.
func (ChatAttOptType) EnumDescriptor() ([]byte, []int) {
	return file_imbotclients_pbdefines_chatroom_proto_rawDescGZIP(), []int{3}
}

type ChrmBanType int32

const (
	ChrmBanType_ChrmBanType_Default ChrmBanType = 0
	ChrmBanType_Ban                 ChrmBanType = 1
	ChrmBanType_Mute                ChrmBanType = 2
	ChrmBanType_Allow               ChrmBanType = 3
)

// Enum value maps for ChrmBanType.
var (
	ChrmBanType_name = map[int32]string{
		0: "ChrmBanType_Default",
		1: "Ban",
		2: "Mute",
		3: "Allow",
	}
	ChrmBanType_value = map[string]int32{
		"ChrmBanType_Default": 0,
		"Ban":                 1,
		"Mute":                2,
		"Allow":               3,
	}
)

func (x ChrmBanType) Enum() *ChrmBanType {
	p := new(ChrmBanType)
	*p = x
	return p
}

func (x ChrmBanType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChrmBanType) Descriptor() protoreflect.EnumDescriptor {
	return file_imbotclients_pbdefines_chatroom_proto_enumTypes[4].Descriptor()
}

func (ChrmBanType) Type() protoreflect.EnumType {
	return &file_imbotclients_pbdefines_chatroom_proto_enumTypes[4]
}

func (x ChrmBanType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChrmBanType.Descriptor instead.
func (ChrmBanType) EnumDescriptor() ([]byte, []int) {
	return file_imbotclients_pbdefines_chatroom_proto_rawDescGZIP(), []int{4}
}

// chatroom
type SyncChatroomReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChatroomId string `protobuf:"bytes,1,opt,name=chatroomId,proto3" json:"chatroomId,omitempty"`
	SyncTime   int64  `protobuf:"varint,2,opt,name=syncTime,proto3" json:"syncTime,omitempty"`
	Count      int32  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *SyncChatroomReq) Reset() {
	*x = SyncChatroomReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_imbotclients_pbdefines_chatroom_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncChatroomReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncChatroomReq) ProtoMessage() {}

func (x *SyncChatroomReq) ProtoReflect() protoreflect.Message {
	mi := &file_imbotclients_pbdefines_chatroom_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncChatroomReq.ProtoReflect.Descriptor instead.
func (*SyncChatroomReq) Descriptor() ([]byte, []int) {
	return file_imbotclients_pbdefines_chatroom_proto_rawDescGZIP(), []int{0}
}

func (x *SyncChatroomReq) GetChatroomId() string {
	if x != nil {
		return x.ChatroomId
	}
	return ""
}

func (x *SyncChatroomReq) GetSyncTime() int64 {
	if x != nil {
		return x.SyncTime
	}
	return 0
}

func (x *SyncChatroomReq) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type SyncChatroomMsgResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msgs []*DownMsg `protobuf:"bytes,1,rep,name=msgs,proto3" json:"msgs,omitempty"`
}

func (x *SyncChatroomMsgResp) Reset() {
	*x = SyncChatroomMsgResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_imbotclients_pbdefines_chatroom_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncChatroomMsgResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncChatroomMsgResp) ProtoMessage() {}

func (x *SyncChatroomMsgResp) ProtoReflect() protoreflect.Message {
	mi := &file_imbotclients_pbdefines_chatroom_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncChatroomMsgResp.ProtoReflect.Descriptor instead.
func (*SyncChatroomMsgResp) Descriptor() ([]byte, []int) {
	return file_imbotclients_pbdefines_chatroom_proto_rawDescGZIP(), []int{1}
}

func (x *SyncChatroomMsgResp) GetMsgs() []*DownMsg {
	if x != nil {
		return x.Msgs
	}
	return nil
}

type SyncChatroomAttResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Atts []*ChatAttItem `protobuf:"bytes,1,rep,name=atts,proto3" json:"atts,omitempty"`
}

func (x *SyncChatroomAttResp) Reset() {
	*x = SyncChatroomAttResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_imbotclients_pbdefines_chatroom_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncChatroomAttResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncChatroomAttResp) ProtoMessage() {}

func (x *SyncChatroomAttResp) ProtoReflect() protoreflect.Message {
	mi := &file_imbotclients_pbdefines_chatroom_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncChatroomAttResp.ProtoReflect.Descriptor instead.
func (*SyncChatroomAttResp) Descriptor() ([]byte, []int) {
	return file_imbotclients_pbdefines_chatroom_proto_rawDescGZIP(), []int{2}
}

func (x *SyncChatroomAttResp) GetAtts() []*ChatAttItem {
	if x != nil {
		return x.Atts
	}
	return nil
}

type SyncChatroomEventResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChrmEvents []*ChrmEvent `protobuf:"bytes,1,rep,name=chrmEvents,proto3" json:"chrmEvents,omitempty"`
}

func (x *SyncChatroomEventResp) Reset() {
	*x = SyncChatroomEventResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_imbotclients_pbdefines_chatroom_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncChatroomEventResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncChatroomEventResp) ProtoMessage() {}

func (x *SyncChatroomEventResp) ProtoReflect() protoreflect.Message {
	mi := &file_imbotclients_pbdefines_chatroom_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncChatroomEventResp.ProtoReflect.Descriptor instead.
func (*SyncChatroomEventResp) Descriptor() ([]byte, []int) {
	return file_imbotclients_pbdefines_chatroom_proto_rawDescGZIP(), []int{3}
}

func (x *SyncChatroomEventResp) GetChrmEvents() []*ChrmEvent {
	if x != nil {
		return x.ChrmEvents
	}
	return nil
}

type ChatroomEvents struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChatId string       `protobuf:"bytes,1,opt,name=chatId,proto3" json:"chatId,omitempty"`
	Events []*ChrmEvent `protobuf:"bytes,2,rep,name=events,proto3" json:"events,omitempty"`
}

func (x *ChatroomEvents) Reset() {
	*x = ChatroomEvents{}
	if protoimpl.UnsafeEnabled {
		mi := &file_imbotclients_pbdefines_chatroom_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatroomEvents) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatroomEvents) ProtoMessage() {}

func (x *ChatroomEvents) ProtoReflect() protoreflect.Message {
	mi := &file_imbotclients_pbdefines_chatroom_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatroomEvents.ProtoReflect.Descriptor instead.
func (*ChatroomEvents) Descriptor() ([]byte, []int) {
	return file_imbotclients_pbdefines_chatroom_proto_rawDescGZIP(), []int{4}
}

func (x *ChatroomEvents) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *ChatroomEvents) GetEvents() []*ChrmEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

type ChrmEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EventType ChrmEventType `protobuf:"varint,1,opt,name=eventType,proto3,enum=ChrmEventType" json:"eventType,omitempty"`
	ChatId    string        `protobuf:"bytes,2,opt,name=chatId,proto3" json:"chatId,omitempty"`
	UserId    string        `protobuf:"bytes,3,opt,name=userId,proto3" json:"userId,omitempty"`
	EventTime int64         `protobuf:"varint,4,opt,name=eventTime,proto3" json:"eventTime,omitempty"`
}

func (x *ChrmEvent) Reset() {
	*x = ChrmEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_imbotclients_pbdefines_chatroom_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChrmEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChrmEvent) ProtoMessage() {}

func (x *ChrmEvent) ProtoReflect() protoreflect.Message {
	mi := &file_imbotclients_pbdefines_chatroom_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChrmEvent.ProtoReflect.Descriptor instead.
func (*ChrmEvent) Descriptor() ([]byte, []int) {
	return file_imbotclients_pbdefines_chatroom_proto_rawDescGZIP(), []int{5}
}

func (x *ChrmEvent) GetEventType() ChrmEventType {
	if x != nil {
		return x.EventType
	}
	return ChrmEventType_Join
}

func (x *ChrmEvent) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *ChrmEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ChrmEvent) GetEventTime() int64 {
	if x != nil {
		return x.EventTime
	}
	return 0
}

type QryChatroomReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChatId      string   `protobuf:"bytes,1,opt,name=chatId,proto3" json:"chatId,omitempty"`
	WithMembers bool     `protobuf:"varint,2,opt,name=withMembers,proto3" json:"withMembers,omitempty"`
	Count       int32    `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	Order       int32    `protobuf:"varint,4,opt,name=order,proto3" json:"order,omitempty"`
	WithAtts    bool     `protobuf:"varint,5,opt,name=withAtts,proto3" json:"withAtts,omitempty"`
	AttKeys     []string `protobuf:"bytes,6,rep,name=attKeys,proto3" json:"attKeys,omitempty"`
}

func (x *QryChatroomReq) Reset() {
	*x = QryChatroomReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_imbotclients_pbdefines_chatroom_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QryChatroomReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QryChatroomReq) ProtoMessage() {}

func (x *QryChatroomReq) ProtoReflect() protoreflect.Message {
	mi := &file_imbotclients_pbdefines_chatroom_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QryChatroomReq.ProtoReflect.Descriptor instead.
func (*QryChatroomReq) Descriptor() ([]byte, []int) {
	return file_imbotclients_pbdefines_chatroom_proto_rawDescGZIP(), []int{6}
}

func (x *QryChatroomReq) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *QryChatroomReq) GetWithMembers() bool {
	if x != nil {
		return x.WithMembers
	}
	return false
}

func (x *QryChatroomReq) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *QryChatroomReq) GetOrder() int32 {
	if x != nil {
		return x.Order
	}
	return 0
}

func (x *QryChatroomReq) GetWithAtts() bool {
	if x != nil {
		return x.WithAtts
	}
	return false
}

func (x *QryChatroomReq) GetAttKeys() []string {
	if x != nil {
		return x.AttKeys
	}
	return nil
}

type ChatroomReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChatId       string `protobuf:"bytes,1,opt,name=chatId,proto3" json:"chatId,omitempty"`
	ChatName     string `protobuf:"bytes,2,opt,name=chatName,proto3" json:"chatName,omitempty"`
	IsAutoCreate bool   `protobuf:"varint,3,opt,name=isAutoCreate,proto3" json:"isAutoCreate,omitempty"`
}

func (x *ChatroomReq) Reset() {
	*x = ChatroomReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_imbotclients_pbdefines_chatroom_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatroomReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatroomReq) ProtoMessage() {}

func (x *ChatroomReq) ProtoReflect() protoreflect.Message {
	mi := &file_imbotclients_pbdefines_chatroom_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatroomReq.ProtoReflect.Descriptor instead.
func (*ChatroomReq) Descriptor() ([]byte, []int) {
	return file_imbotclients_pbdefines_chatroom_proto_rawDescGZIP(), []int{7}
}

func (x *ChatroomReq) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *ChatroomReq) GetChatName() string {
	if x != nil {
		return x.ChatName
	}
	return ""
}

func (x *ChatroomReq) GetIsAutoCreate() bool {
	if x != nil {
		return x.IsAutoCreate
	}
	return false
}

type ChatroomInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChatId        string            `protobuf:"bytes,1,opt,name=chatId,proto3" json:"chatId,omitempty"`
	ChatName      string            `protobuf:"bytes,2,opt,name=chatName,proto3" json:"chatName,omitempty"`
	Members       []*ChatroomMember `protobuf:"bytes,3,rep,name=members,proto3" json:"members,omitempty"`
	Atts          []*ChatAttItem    `protobuf:"bytes,4,rep,name=atts,proto3" json:"atts,omitempty"`
	MemberCount   int32             `protobuf:"varint,5,opt,name=memberCount,proto3" json:"memberCount,omitempty"`
	IsMute        bool              `protobuf:"varint,6,opt,name=isMute,proto3" json:"isMute,omitempty"`
	IsAutoDestroy bool              `protobuf:"varint,7,opt,name=isAutoDestroy,proto3" json:"isAutoDestroy,omitempty"`
}

func (x *ChatroomInfo) Reset() {
	*x = ChatroomInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_imbotclients_pbdefines_chatroom_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatroomInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatroomInfo) ProtoMessage() {}

func (x *ChatroomInfo) ProtoReflect() protoreflect.Message {
	mi := &file_imbotclients_pbdefines_chatroom_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatroomInfo.ProtoReflect.Descriptor instead.
func (*ChatroomInfo) Descriptor() ([]byte, []int) {
	return file_imbotclients_pbdefines_chatroom_proto_rawDescGZIP(), []int{8}
}

func (x *ChatroomInfo) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *ChatroomInfo) GetChatName() string {
	if x != nil {
		return x.ChatName
	}
	return ""
}

func (x *ChatroomInfo) GetMembers() []*ChatroomMember {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *ChatroomInfo) GetAtts() []*ChatAttItem {
	if x != nil {
		return x.Atts
	}
	return nil
}

func (x *ChatroomInfo) GetMemberCount() int32 {
	if x != nil {
		return x.MemberCount
	}
	return 0
}

func (x *ChatroomInfo) GetIsMute() bool {
	if x != nil {
		return x.IsMute
	}
	return false
}

func (x *ChatroomInfo) GetIsAutoDestroy() bool {
	if x != nil {
		return x.IsAutoDestroy
	}
	return false
}

type ChatMsgNode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeName string `protobuf:"bytes,1,opt,name=nodeName,proto3" json:"nodeName,omitempty"`
	Method   string `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
}

func (x *ChatMsgNode) Reset() {
	*x = ChatMsgNode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_imbotclients_pbdefines_chatroom_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatMsgNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMsgNode) ProtoMessage() {}

func (x *ChatMsgNode) ProtoReflect() protoreflect.Message {
	mi := &file_imbotclients_pbdefines_chatroom_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMsgNode.ProtoReflect.Descriptor instead.
func (*ChatMsgNode) Descriptor() ([]byte, []int) {
	return file_imbotclients_pbdefines_chatroom_proto_rawDescGZIP(), []int{9}
}

func (x *ChatMsgNode) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *ChatMsgNode) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

type ChatroomMember struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MemberId   string `protobuf:"bytes,1,opt,name=memberId,proto3" json:"memberId,omitempty"`
	MemberName string `protobuf:"bytes,2,opt,name=memberName,proto3" json:"memberName,omitempty"`
	AddedTime  int64  `protobuf:"varint,3,opt,name=addedTime,proto3" json:"addedTime,omitempty"`
}

func (x *ChatroomMember) Reset() {
	*x = ChatroomMember{}
	if protoimpl.UnsafeEnabled {
		mi := &file_imbotclients_pbdefines_chatroom_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatroomMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatroomMember) ProtoMessage() {}

func (x *ChatroomMember) ProtoReflect() protoreflect.Message {
	mi := &file_imbotclients_pbdefines_chatroom_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatroomMember.ProtoReflect.Descriptor instead.
func (*ChatroomMember) Descriptor() ([]byte, []int) {
	return file_imbotclients_pbdefines_chatroom_proto_rawDescGZIP(), []int{10}
}

func (x *ChatroomMember) GetMemberId() string {
	if x != nil {
		return x.MemberId
	}
	return ""
}

func (x *ChatroomMember) GetMemberName() string {
	if x != nil {
		return x.MemberName
	}
	return ""
}

func (x *ChatroomMember) GetAddedTime() int64 {
	if x != nil {
		return x.AddedTime
	}
	return 0
}

type ChrmDispatchReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChatId       string           `protobuf:"bytes,1,opt,name=chatId,proto3" json:"chatId,omitempty"`
	DispatchType ChrmDispatchType `protobuf:"varint,2,opt,name=dispatchType,proto3,enum=ChrmDispatchType" json:"dispatchType,omitempty"`
}

func (x *ChrmDispatchReq) Reset() {
	*x = ChrmDispatchReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_imbotclients_pbdefines_chatroom_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChrmDispatchReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChrmDispatchReq) ProtoMessage() {}

func (x *ChrmDispatchReq) ProtoReflect() protoreflect.Message {
	mi := &file_imbotclients_pbdefines_chatroom_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChrmDispatchReq.ProtoReflect.Descriptor instead.
func (*ChrmDispatchReq) Descriptor() ([]byte, []int) {
	return file_imbotclients_pbdefines_chatroom_proto_rawDescGZIP(), []int{11}
}

func (x *ChrmDispatchReq) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *ChrmDispatchReq) GetDispatchType() ChrmDispatchType {
	if x != nil {
		return x.DispatchType
	}
	return ChrmDispatchType_CreateChatroom
}

type ChatMembersDispatchReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChatId       string                  `protobuf:"bytes,1,opt,name=chatId,proto3" json:"chatId,omitempty"`
	MemberIds    []string                `protobuf:"bytes,2,rep,name=memberIds,proto3" json:"memberIds,omitempty"`
	DispatchType ChatMembersDispatchType `protobuf:"varint,3,opt,name=dispatchType,proto3,enum=ChatMembersDispatchType" json:"dispatchType,omitempty"`
}

func (x *ChatMembersDispatchReq) Reset() {
	*x = ChatMembersDispatchReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_imbotclients_pbdefines_chatroom_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatMembersDispatchReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMembersDispatchReq) ProtoMessage() {}

func (x *ChatMembersDispatchReq) ProtoReflect() protoreflect.Message {
	mi := &file_imbotclients_pbdefines_chatroom_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMembersDispatchReq.ProtoReflect.Descriptor instead.
func (*ChatMembersDispatchReq) Descriptor() ([]byte, []int) {
	return file_imbotclients_pbdefines_chatroom_proto_rawDescGZIP(), []int{12}
}

func (x *ChatMembersDispatchReq) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *ChatMembersDispatchReq) GetMemberIds() []string {
	if x != nil {
		return x.MemberIds
	}
	return nil
}

func (x *ChatMembersDispatchReq) GetDispatchType() ChatMembersDispatchType {
	if x != nil {
		return x.DispatchType
	}
	return ChatMembersDispatchType_DispatchDefault
}

type ChatAttReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key       string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value     string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	IsForce   bool   `protobuf:"varint,3,opt,name=isForce,proto3" json:"isForce,omitempty"`
	IsAutoDel bool   `protobuf:"varint,4,opt,name=isAutoDel,proto3" json:"isAutoDel,omitempty"`
	Msg       *UpMsg `protobuf:"bytes,5,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *ChatAttReq) Reset() {
	*x = ChatAttReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_imbotclients_pbdefines_chatroom_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatAttReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatAttReq) ProtoMessage() {}

func (x *ChatAttReq) ProtoReflect() protoreflect.Message {
	mi := &file_imbotclients_pbdefines_chatroom_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatAttReq.ProtoReflect.Descriptor instead.
func (*ChatAttReq) Descriptor() ([]byte, []int) {
	return file_imbotclients_pbdefines_chatroom_proto_rawDescGZIP(), []int{13}
}

func (x *ChatAttReq) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ChatAttReq) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *ChatAttReq) GetIsForce() bool {
	if x != nil {
		return x.IsForce
	}
	return false
}

func (x *ChatAttReq) GetIsAutoDel() bool {
	if x != nil {
		return x.IsAutoDel
	}
	return false
}

func (x *ChatAttReq) GetMsg() *UpMsg {
	if x != nil {
		return x.Msg
	}
	return nil
}

type ChatAttResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key     string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Code    int32  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	AttTime int64  `protobuf:"varint,3,opt,name=attTime,proto3" json:"attTime,omitempty"`
	MsgCode int32  `protobuf:"varint,11,opt,name=msgCode,proto3" json:"msgCode,omitempty"`
	MsgId   string `protobuf:"bytes,12,opt,name=msgId,proto3" json:"msgId,omitempty"`
	MsgTime int64  `protobuf:"varint,13,opt,name=msgTime,proto3" json:"msgTime,omitempty"`
	MsgSeq  int64  `protobuf:"varint,14,opt,name=msgSeq,proto3" json:"msgSeq,omitempty"`
}

func (x *ChatAttResp) Reset() {
	*x = ChatAttResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_imbotclients_pbdefines_chatroom_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatAttResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatAttResp) ProtoMessage() {}

func (x *ChatAttResp) ProtoReflect() protoreflect.Message {
	mi := &file_imbotclients_pbdefines_chatroom_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatAttResp.ProtoReflect.Descriptor instead.
func (*ChatAttResp) Descriptor() ([]byte, []int) {
	return file_imbotclients_pbdefines_chatroom_proto_rawDescGZIP(), []int{14}
}

func (x *ChatAttResp) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ChatAttResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ChatAttResp) GetAttTime() int64 {
	if x != nil {
		return x.AttTime
	}
	return 0
}

func (x *ChatAttResp) GetMsgCode() int32 {
	if x != nil {
		return x.MsgCode
	}
	return 0
}

func (x *ChatAttResp) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

func (x *ChatAttResp) GetMsgTime() int64 {
	if x != nil {
		return x.MsgTime
	}
	return 0
}

func (x *ChatAttResp) GetMsgSeq() int64 {
	if x != nil {
		return x.MsgSeq
	}
	return 0
}

type ChatAttBatchReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Atts []*ChatAttReq `protobuf:"bytes,1,rep,name=atts,proto3" json:"atts,omitempty"`
}

func (x *ChatAttBatchReq) Reset() {
	*x = ChatAttBatchReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_imbotclients_pbdefines_chatroom_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatAttBatchReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatAttBatchReq) ProtoMessage() {}

func (x *ChatAttBatchReq) ProtoReflect() protoreflect.Message {
	mi := &file_imbotclients_pbdefines_chatroom_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatAttBatchReq.ProtoReflect.Descriptor instead.
func (*ChatAttBatchReq) Descriptor() ([]byte, []int) {
	return file_imbotclients_pbdefines_chatroom_proto_rawDescGZIP(), []int{15}
}

func (x *ChatAttBatchReq) GetAtts() []*ChatAttReq {
	if x != nil {
		return x.Atts
	}
	return nil
}

type ChatAttBatchResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AttResps []*ChatAttResp `protobuf:"bytes,1,rep,name=attResps,proto3" json:"attResps,omitempty"`
}

func (x *ChatAttBatchResp) Reset() {
	*x = ChatAttBatchResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_imbotclients_pbdefines_chatroom_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatAttBatchResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatAttBatchResp) ProtoMessage() {}

func (x *ChatAttBatchResp) ProtoReflect() protoreflect.Message {
	mi := &file_imbotclients_pbdefines_chatroom_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatAttBatchResp.ProtoReflect.Descriptor instead.
func (*ChatAttBatchResp) Descriptor() ([]byte, []int) {
	return file_imbotclients_pbdefines_chatroom_proto_rawDescGZIP(), []int{16}
}

func (x *ChatAttBatchResp) GetAttResps() []*ChatAttResp {
	if x != nil {
		return x.AttResps
	}
	return nil
}

type ChatAttItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key     string         `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value   string         `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	AttTime int64          `protobuf:"varint,3,opt,name=attTime,proto3" json:"attTime,omitempty"`
	UserId  string         `protobuf:"bytes,4,opt,name=userId,proto3" json:"userId,omitempty"`
	OptType ChatAttOptType `protobuf:"varint,5,opt,name=optType,proto3,enum=ChatAttOptType" json:"optType,omitempty"`
}

func (x *ChatAttItem) Reset() {
	*x = ChatAttItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_imbotclients_pbdefines_chatroom_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatAttItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatAttItem) ProtoMessage() {}

func (x *ChatAttItem) ProtoReflect() protoreflect.Message {
	mi := &file_imbotclients_pbdefines_chatroom_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatAttItem.ProtoReflect.Descriptor instead.
func (*ChatAttItem) Descriptor() ([]byte, []int) {
	return file_imbotclients_pbdefines_chatroom_proto_rawDescGZIP(), []int{17}
}

func (x *ChatAttItem) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ChatAttItem) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *ChatAttItem) GetAttTime() int64 {
	if x != nil {
		return x.AttTime
	}
	return 0
}

func (x *ChatAttItem) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ChatAttItem) GetOptType() ChatAttOptType {
	if x != nil {
		return x.OptType
	}
	return ChatAttOptType_ChatAttOpt_Default
}

type ChatAtts struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChatId     string         `protobuf:"bytes,1,opt,name=chatId,proto3" json:"chatId,omitempty"`
	Atts       []*ChatAttItem `protobuf:"bytes,2,rep,name=atts,proto3" json:"atts,omitempty"`
	IsComplete bool           `protobuf:"varint,3,opt,name=isComplete,proto3" json:"isComplete,omitempty"`
	IsFinished bool           `protobuf:"varint,4,opt,name=isFinished,proto3" json:"isFinished,omitempty"`
}

func (x *ChatAtts) Reset() {
	*x = ChatAtts{}
	if protoimpl.UnsafeEnabled {
		mi := &file_imbotclients_pbdefines_chatroom_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatAtts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatAtts) ProtoMessage() {}

func (x *ChatAtts) ProtoReflect() protoreflect.Message {
	mi := &file_imbotclients_pbdefines_chatroom_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatAtts.ProtoReflect.Descriptor instead.
func (*ChatAtts) Descriptor() ([]byte, []int) {
	return file_imbotclients_pbdefines_chatroom_proto_rawDescGZIP(), []int{18}
}

func (x *ChatAtts) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *ChatAtts) GetAtts() []*ChatAttItem {
	if x != nil {
		return x.Atts
	}
	return nil
}

func (x *ChatAtts) GetIsComplete() bool {
	if x != nil {
		return x.IsComplete
	}
	return false
}

func (x *ChatAtts) GetIsFinished() bool {
	if x != nil {
		return x.IsFinished
	}
	return false
}

type BatchBanUserReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChatId    string      `protobuf:"bytes,1,opt,name=chatId,proto3" json:"chatId,omitempty"`
	BanType   ChrmBanType `protobuf:"varint,2,opt,name=banType,proto3,enum=ChrmBanType" json:"banType,omitempty"`
	MemberIds []string    `protobuf:"bytes,3,rep,name=memberIds,proto3" json:"memberIds,omitempty"`
	EndTime   int64       `protobuf:"varint,4,opt,name=endTime,proto3" json:"endTime,omitempty"`
	IsDelete  bool        `protobuf:"varint,5,opt,name=isDelete,proto3" json:"isDelete,omitempty"`
}

func (x *BatchBanUserReq) Reset() {
	*x = BatchBanUserReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_imbotclients_pbdefines_chatroom_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BatchBanUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchBanUserReq) ProtoMessage() {}

func (x *BatchBanUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_imbotclients_pbdefines_chatroom_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchBanUserReq.ProtoReflect.Descriptor instead.
func (*BatchBanUserReq) Descriptor() ([]byte, []int) {
	return file_imbotclients_pbdefines_chatroom_proto_rawDescGZIP(), []int{19}
}

func (x *BatchBanUserReq) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *BatchBanUserReq) GetBanType() ChrmBanType {
	if x != nil {
		return x.BanType
	}
	return ChrmBanType_ChrmBanType_Default
}

func (x *BatchBanUserReq) GetMemberIds() []string {
	if x != nil {
		return x.MemberIds
	}
	return nil
}

func (x *BatchBanUserReq) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *BatchBanUserReq) GetIsDelete() bool {
	if x != nil {
		return x.IsDelete
	}
	return false
}

type QryChrmBanUsersReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChatId  string      `protobuf:"bytes,1,opt,name=chatId,proto3" json:"chatId,omitempty"`
	BanType ChrmBanType `protobuf:"varint,2,opt,name=banType,proto3,enum=ChrmBanType" json:"banType,omitempty"`
	Offset  string      `protobuf:"bytes,3,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit   int64       `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *QryChrmBanUsersReq) Reset() {
	*x = QryChrmBanUsersReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_imbotclients_pbdefines_chatroom_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QryChrmBanUsersReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QryChrmBanUsersReq) ProtoMessage() {}

func (x *QryChrmBanUsersReq) ProtoReflect() protoreflect.Message {
	mi := &file_imbotclients_pbdefines_chatroom_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QryChrmBanUsersReq.ProtoReflect.Descriptor instead.
func (*QryChrmBanUsersReq) Descriptor() ([]byte, []int) {
	return file_imbotclients_pbdefines_chatroom_proto_rawDescGZIP(), []int{20}
}

func (x *QryChrmBanUsersReq) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *QryChrmBanUsersReq) GetBanType() ChrmBanType {
	if x != nil {
		return x.BanType
	}
	return ChrmBanType_ChrmBanType_Default
}

func (x *QryChrmBanUsersReq) GetOffset() string {
	if x != nil {
		return x.Offset
	}
	return ""
}

func (x *QryChrmBanUsersReq) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type QryChrmBanUsersResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChatId  string           `protobuf:"bytes,1,opt,name=chatId,proto3" json:"chatId,omitempty"`
	BanType ChrmBanType      `protobuf:"varint,2,opt,name=BanType,proto3,enum=ChrmBanType" json:"BanType,omitempty"`
	Members []*ChrmBanMember `protobuf:"bytes,3,rep,name=members,proto3" json:"members,omitempty"`
	Offset  string           `protobuf:"bytes,4,opt,name=offset,proto3" json:"offset,omitempty"`
}

func (x *QryChrmBanUsersResp) Reset() {
	*x = QryChrmBanUsersResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_imbotclients_pbdefines_chatroom_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QryChrmBanUsersResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QryChrmBanUsersResp) ProtoMessage() {}

func (x *QryChrmBanUsersResp) ProtoReflect() protoreflect.Message {
	mi := &file_imbotclients_pbdefines_chatroom_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QryChrmBanUsersResp.ProtoReflect.Descriptor instead.
func (*QryChrmBanUsersResp) Descriptor() ([]byte, []int) {
	return file_imbotclients_pbdefines_chatroom_proto_rawDescGZIP(), []int{21}
}

func (x *QryChrmBanUsersResp) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *QryChrmBanUsersResp) GetBanType() ChrmBanType {
	if x != nil {
		return x.BanType
	}
	return ChrmBanType_ChrmBanType_Default
}

func (x *QryChrmBanUsersResp) GetMembers() []*ChrmBanMember {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *QryChrmBanUsersResp) GetOffset() string {
	if x != nil {
		return x.Offset
	}
	return ""
}

type ChrmBanMember struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MemberId    string `protobuf:"bytes,1,opt,name=memberId,proto3" json:"memberId,omitempty"`
	CreatedTime int64  `protobuf:"varint,2,opt,name=createdTime,proto3" json:"createdTime,omitempty"`
	EndTime     int64  `protobuf:"varint,3,opt,name=endTime,proto3" json:"endTime,omitempty"`
}

func (x *ChrmBanMember) Reset() {
	*x = ChrmBanMember{}
	if protoimpl.UnsafeEnabled {
		mi := &file_imbotclients_pbdefines_chatroom_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChrmBanMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChrmBanMember) ProtoMessage() {}

func (x *ChrmBanMember) ProtoReflect() protoreflect.Message {
	mi := &file_imbotclients_pbdefines_chatroom_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChrmBanMember.ProtoReflect.Descriptor instead.
func (*ChrmBanMember) Descriptor() ([]byte, []int) {
	return file_imbotclients_pbdefines_chatroom_proto_rawDescGZIP(), []int{22}
}

func (x *ChrmBanMember) GetMemberId() string {
	if x != nil {
		return x.MemberId
	}
	return ""
}

func (x *ChrmBanMember) GetCreatedTime() int64 {
	if x != nil {
		return x.CreatedTime
	}
	return 0
}

func (x *ChrmBanMember) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

type ChrmMemberIds struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChatId    string   `protobuf:"bytes,1,opt,name=chatId,proto3" json:"chatId,omitempty"`
	MemberIds []string `protobuf:"bytes,2,rep,name=memberIds,proto3" json:"memberIds,omitempty"`
}

func (x *ChrmMemberIds) Reset() {
	*x = ChrmMemberIds{}
	if protoimpl.UnsafeEnabled {
		mi := &file_imbotclients_pbdefines_chatroom_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChrmMemberIds) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChrmMemberIds) ProtoMessage() {}

func (x *ChrmMemberIds) ProtoReflect() protoreflect.Message {
	mi := &file_imbotclients_pbdefines_chatroom_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChrmMemberIds.ProtoReflect.Descriptor instead.
func (*ChrmMemberIds) Descriptor() ([]byte, []int) {
	return file_imbotclients_pbdefines_chatroom_proto_rawDescGZIP(), []int{23}
}

func (x *ChrmMemberIds) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *ChrmMemberIds) GetMemberIds() []string {
	if x != nil {
		return x.MemberIds
	}
	return nil
}

type ChrmMemberExistItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MemberId string `protobuf:"bytes,1,opt,name=memberId,proto3" json:"memberId,omitempty"`
	Exist    bool   `protobuf:"varint,2,opt,name=exist,proto3" json:"exist,omitempty"`
}

func (x *ChrmMemberExistItem) Reset() {
	*x = ChrmMemberExistItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_imbotclients_pbdefines_chatroom_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChrmMemberExistItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChrmMemberExistItem) ProtoMessage() {}

func (x *ChrmMemberExistItem) ProtoReflect() protoreflect.Message {
	mi := &file_imbotclients_pbdefines_chatroom_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChrmMemberExistItem.ProtoReflect.Descriptor instead.
func (*ChrmMemberExistItem) Descriptor() ([]byte, []int) {
	return file_imbotclients_pbdefines_chatroom_proto_rawDescGZIP(), []int{24}
}

func (x *ChrmMemberExistItem) GetMemberId() string {
	if x != nil {
		return x.MemberId
	}
	return ""
}

func (x *ChrmMemberExistItem) GetExist() bool {
	if x != nil {
		return x.Exist
	}
	return false
}

type ChrmMembersExistResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*ChrmMemberExistItem `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *ChrmMembersExistResp) Reset() {
	*x = ChrmMembersExistResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_imbotclients_pbdefines_chatroom_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChrmMembersExistResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChrmMembersExistResp) ProtoMessage() {}

func (x *ChrmMembersExistResp) ProtoReflect() protoreflect.Message {
	mi := &file_imbotclients_pbdefines_chatroom_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChrmMembersExistResp.ProtoReflect.Descriptor instead.
func (*ChrmMembersExistResp) Descriptor() ([]byte, []int) {
	return file_imbotclients_pbdefines_chatroom_proto_rawDescGZIP(), []int{25}
}

func (x *ChrmMembersExistResp) GetItems() []*ChrmMemberExistItem {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_imbotclients_pbdefines_chatroom_proto protoreflect.FileDescriptor

var file_imbotclients_pbdefines_chatroom_proto_rawDesc = []byte{
	0x0a, 0x25, 0x69, 0x6d, 0x62, 0x6f, 0x74, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x73, 0x2f, 0x70,
	0x62, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x65, 0x73, 0x2f, 0x63, 0x68, 0x61, 0x74, 0x72, 0x6f, 0x6f,
	0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x28, 0x69, 0x6d, 0x62, 0x6f, 0x74, 0x63, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x73, 0x2f, 0x70, 0x62, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x65, 0x73, 0x2f,
	0x61, 0x70, 0x70, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x63, 0x0a, 0x0f, 0x53, 0x79, 0x6e, 0x63, 0x43, 0x68, 0x61, 0x74, 0x72, 0x6f, 0x6f,
	0x6d, 0x52, 0x65, 0x71, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x68, 0x61, 0x74, 0x72, 0x6f, 0x6f, 0x6d,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x68, 0x61, 0x74, 0x72, 0x6f,
	0x6f, 0x6d, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x79, 0x6e, 0x63, 0x54, 0x69, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x73, 0x79, 0x6e, 0x63, 0x54, 0x69, 0x6d, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x33, 0x0a, 0x13, 0x53, 0x79, 0x6e, 0x63, 0x43, 0x68,
	0x61, 0x74, 0x72, 0x6f, 0x6f, 0x6d, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x73, 0x70, 0x12, 0x1c, 0x0a,
	0x04, 0x6d, 0x73, 0x67, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x44, 0x6f,
	0x77, 0x6e, 0x4d, 0x73, 0x67, 0x52, 0x04, 0x6d, 0x73, 0x67, 0x73, 0x22, 0x37, 0x0a, 0x13, 0x53,
	0x79, 0x6e, 0x63, 0x43, 0x68, 0x61, 0x74, 0x72, 0x6f, 0x6f, 0x6d, 0x41, 0x74, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x20, 0x0a, 0x04, 0x61, 0x74, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0c, 0x2e, 0x43, 0x68, 0x61, 0x74, 0x41, 0x74, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x04,
	0x61, 0x74, 0x74, 0x73, 0x22, 0x43, 0x0a, 0x15, 0x53, 0x79, 0x6e, 0x63, 0x43, 0x68, 0x61, 0x74,
	0x72, 0x6f, 0x6f, 0x6d, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x2a, 0x0a,
	0x0a, 0x63, 0x68, 0x72, 0x6d, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0a, 0x2e, 0x43, 0x68, 0x72, 0x6d, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x0a, 0x63,
	0x68, 0x72, 0x6d, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x22, 0x4c, 0x0a, 0x0e, 0x43, 0x68, 0x61,
	0x74, 0x72, 0x6f, 0x6f, 0x6d, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x63,
	0x68, 0x61, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x68, 0x61,
	0x74, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x06, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x43, 0x68, 0x72, 0x6d, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52,
	0x06, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x22, 0x87, 0x01, 0x0a, 0x09, 0x43, 0x68, 0x72, 0x6d,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x2c, 0x0a, 0x09, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79,
	0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x43, 0x68, 0x72, 0x6d, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x09, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x68, 0x61, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x68, 0x61, 0x74, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x69, 0x6d, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x69, 0x6d,
	0x65, 0x22, 0xac, 0x01, 0x0a, 0x0e, 0x51, 0x72, 0x79, 0x43, 0x68, 0x61, 0x74, 0x72, 0x6f, 0x6f,
	0x6d, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x68, 0x61, 0x74, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x68, 0x61, 0x74, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b,
	0x77, 0x69, 0x74, 0x68, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x0b, 0x77, 0x69, 0x74, 0x68, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x12, 0x14,
	0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x77, 0x69,
	0x74, 0x68, 0x41, 0x74, 0x74, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x77, 0x69,
	0x74, 0x68, 0x41, 0x74, 0x74, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x74, 0x74, 0x4b, 0x65, 0x79,
	0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x61, 0x74, 0x74, 0x4b, 0x65, 0x79, 0x73,
	0x22, 0x65, 0x0a, 0x0b, 0x43, 0x68, 0x61, 0x74, 0x72, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x71, 0x12,
	0x16, 0x0a, 0x06, 0x63, 0x68, 0x61, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x63, 0x68, 0x61, 0x74, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x68, 0x61, 0x74, 0x4e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x68, 0x61, 0x74, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x69, 0x73, 0x41, 0x75, 0x74, 0x6f, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0c, 0x69, 0x73, 0x41, 0x75, 0x74,
	0x6f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x22, 0xef, 0x01, 0x0a, 0x0c, 0x43, 0x68, 0x61, 0x74,
	0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x68, 0x61, 0x74,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x68, 0x61, 0x74, 0x49, 0x64,
	0x12, 0x1a, 0x0a, 0x08, 0x63, 0x68, 0x61, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x63, 0x68, 0x61, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x29, 0x0a, 0x07,
	0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e,
	0x43, 0x68, 0x61, 0x74, 0x72, 0x6f, 0x6f, 0x6d, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x07,
	0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x12, 0x20, 0x0a, 0x04, 0x61, 0x74, 0x74, 0x73, 0x18,
	0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x43, 0x68, 0x61, 0x74, 0x41, 0x74, 0x74, 0x49,
	0x74, 0x65, 0x6d, 0x52, 0x04, 0x61, 0x74, 0x74, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x6d, 0x65, 0x6d,
	0x62, 0x65, 0x72, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b,
	0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x69,
	0x73, 0x4d, 0x75, 0x74, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x69, 0x73, 0x4d,
	0x75, 0x74, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x69, 0x73, 0x41, 0x75, 0x74, 0x6f, 0x44, 0x65, 0x73,
	0x74, 0x72, 0x6f, 0x79, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0d, 0x69, 0x73, 0x41, 0x75,
	0x74, 0x6f, 0x44, 0x65, 0x73, 0x74, 0x72, 0x6f, 0x79, 0x22, 0x41, 0x0a, 0x0b, 0x43, 0x68, 0x61,
	0x74, 0x4d, 0x73, 0x67, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x6f, 0x64, 0x65,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x6f, 0x64, 0x65,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x22, 0x6a, 0x0a, 0x0e,
	0x43, 0x68, 0x61, 0x74, 0x72, 0x6f, 0x6f, 0x6d, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x1a,
	0x0a, 0x08, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x6d, 0x65,
	0x6d, 0x62, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x64,
	0x64, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x61,
	0x64, 0x64, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x60, 0x0a, 0x0f, 0x43, 0x68, 0x72, 0x6d,
	0x44, 0x69, 0x73, 0x70, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x63,
	0x68, 0x61, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x68, 0x61,
	0x74, 0x49, 0x64, 0x12, 0x35, 0x0a, 0x0c, 0x64, 0x69, 0x73, 0x70, 0x61, 0x74, 0x63, 0x68, 0x54,
	0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x43, 0x68, 0x72, 0x6d,
	0x44, 0x69, 0x73, 0x70, 0x61, 0x74, 0x63, 0x68, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0c, 0x64, 0x69,
	0x73, 0x70, 0x61, 0x74, 0x63, 0x68, 0x54, 0x79, 0x70, 0x65, 0x22, 0x8c, 0x01, 0x0a, 0x16, 0x43,
	0x68, 0x61, 0x74, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x44, 0x69, 0x73, 0x70, 0x61, 0x74,
	0x63, 0x68, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x68, 0x61, 0x74, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x68, 0x61, 0x74, 0x49, 0x64, 0x12, 0x1c, 0x0a,
	0x09, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x49, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x09, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x49, 0x64, 0x73, 0x12, 0x3c, 0x0a, 0x0c, 0x64,
	0x69, 0x73, 0x70, 0x61, 0x74, 0x63, 0x68, 0x54, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x18, 0x2e, 0x43, 0x68, 0x61, 0x74, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x44,
	0x69, 0x73, 0x70, 0x61, 0x74, 0x63, 0x68, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0c, 0x64, 0x69, 0x73,
	0x70, 0x61, 0x74, 0x63, 0x68, 0x54, 0x79, 0x70, 0x65, 0x22, 0x86, 0x01, 0x0a, 0x0a, 0x43, 0x68,
	0x61, 0x74, 0x41, 0x74, 0x74, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x69, 0x73, 0x46, 0x6f, 0x72, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x07, 0x69, 0x73, 0x46, 0x6f, 0x72, 0x63, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x69, 0x73,
	0x41, 0x75, 0x74, 0x6f, 0x44, 0x65, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x69,
	0x73, 0x41, 0x75, 0x74, 0x6f, 0x44, 0x65, 0x6c, 0x12, 0x18, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x06, 0x2e, 0x55, 0x70, 0x4d, 0x73, 0x67, 0x52, 0x03, 0x6d,
	0x73, 0x67, 0x22, 0xaf, 0x01, 0x0a, 0x0b, 0x43, 0x68, 0x61, 0x74, 0x41, 0x74, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6b, 0x65, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x74, 0x74, 0x54,
	0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x61, 0x74, 0x74, 0x54, 0x69,
	0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x73, 0x67, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x0b, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x07, 0x6d, 0x73, 0x67, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x6d, 0x73, 0x67, 0x49, 0x64, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6d, 0x73, 0x67,
	0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x73, 0x67, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x0d, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x07, 0x6d, 0x73, 0x67, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x6d, 0x73, 0x67, 0x53, 0x65, 0x71, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x6d, 0x73,
	0x67, 0x53, 0x65, 0x71, 0x22, 0x32, 0x0a, 0x0f, 0x43, 0x68, 0x61, 0x74, 0x41, 0x74, 0x74, 0x42,
	0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x71, 0x12, 0x1f, 0x0a, 0x04, 0x61, 0x74, 0x74, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x43, 0x68, 0x61, 0x74, 0x41, 0x74, 0x74, 0x52,
	0x65, 0x71, 0x52, 0x04, 0x61, 0x74, 0x74, 0x73, 0x22, 0x3c, 0x0a, 0x10, 0x43, 0x68, 0x61, 0x74,
	0x41, 0x74, 0x74, 0x42, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x12, 0x28, 0x0a, 0x08,
	0x61, 0x74, 0x74, 0x52, 0x65, 0x73, 0x70, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c,
	0x2e, 0x43, 0x68, 0x61, 0x74, 0x41, 0x74, 0x74, 0x52, 0x65, 0x73, 0x70, 0x52, 0x08, 0x61, 0x74,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x73, 0x22, 0x92, 0x01, 0x0a, 0x0b, 0x43, 0x68, 0x61, 0x74, 0x41,
	0x74, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x61, 0x74, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x07, 0x61, 0x74, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x12, 0x29, 0x0a, 0x07, 0x6f, 0x70, 0x74, 0x54, 0x79, 0x70, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x0f, 0x2e, 0x43, 0x68, 0x61, 0x74, 0x41, 0x74, 0x74, 0x4f, 0x70, 0x74, 0x54, 0x79,
	0x70, 0x65, 0x52, 0x07, 0x6f, 0x70, 0x74, 0x54, 0x79, 0x70, 0x65, 0x22, 0x84, 0x01, 0x0a, 0x08,
	0x43, 0x68, 0x61, 0x74, 0x41, 0x74, 0x74, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x68, 0x61, 0x74,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x68, 0x61, 0x74, 0x49, 0x64,
	0x12, 0x20, 0x0a, 0x04, 0x61, 0x74, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c,
	0x2e, 0x43, 0x68, 0x61, 0x74, 0x41, 0x74, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x04, 0x61, 0x74,
	0x74, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x69, 0x73, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x69, 0x73, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65,
	0x74, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x69, 0x73, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x65, 0x64,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x69, 0x73, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68,
	0x65, 0x64, 0x22, 0xa5, 0x01, 0x0a, 0x0f, 0x42, 0x61, 0x74, 0x63, 0x68, 0x42, 0x61, 0x6e, 0x55,
	0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x68, 0x61, 0x74, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x68, 0x61, 0x74, 0x49, 0x64, 0x12, 0x26,
	0x0a, 0x07, 0x62, 0x61, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x0c, 0x2e, 0x43, 0x68, 0x72, 0x6d, 0x42, 0x61, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x07, 0x62,
	0x61, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72,
	0x49, 0x64, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x6d, 0x65, 0x6d, 0x62, 0x65,
	0x72, 0x49, 0x64, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1a,
	0x0a, 0x08, 0x69, 0x73, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x08, 0x69, 0x73, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x22, 0x82, 0x01, 0x0a, 0x12, 0x51,
	0x72, 0x79, 0x43, 0x68, 0x72, 0x6d, 0x42, 0x61, 0x6e, 0x55, 0x73, 0x65, 0x72, 0x73, 0x52, 0x65,
	0x71, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x68, 0x61, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x63, 0x68, 0x61, 0x74, 0x49, 0x64, 0x12, 0x26, 0x0a, 0x07, 0x62, 0x61, 0x6e,
	0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0c, 0x2e, 0x43, 0x68, 0x72,
	0x6d, 0x42, 0x61, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x07, 0x62, 0x61, 0x6e, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d,
	0x69, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x22,
	0x97, 0x01, 0x0a, 0x13, 0x51, 0x72, 0x79, 0x43, 0x68, 0x72, 0x6d, 0x42, 0x61, 0x6e, 0x55, 0x73,
	0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x68, 0x61, 0x74, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x68, 0x61, 0x74, 0x49, 0x64, 0x12,
	0x26, 0x0a, 0x07, 0x42, 0x61, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x0c, 0x2e, 0x43, 0x68, 0x72, 0x6d, 0x42, 0x61, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x07,
	0x42, 0x61, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x28, 0x0a, 0x07, 0x6d, 0x65, 0x6d, 0x62, 0x65,
	0x72, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x43, 0x68, 0x72, 0x6d, 0x42,
	0x61, 0x6e, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x07, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72,
	0x73, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x22, 0x67, 0x0a, 0x0d, 0x43, 0x68, 0x72,
	0x6d, 0x42, 0x61, 0x6e, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x6d, 0x65,
	0x6d, 0x62, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6d, 0x65,
	0x6d, 0x62, 0x65, 0x72, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x64, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x6e, 0x64, 0x54,
	0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x65, 0x6e, 0x64, 0x54, 0x69,
	0x6d, 0x65, 0x22, 0x45, 0x0a, 0x0d, 0x43, 0x68, 0x72, 0x6d, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72,
	0x49, 0x64, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x68, 0x61, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x68, 0x61, 0x74, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x6d,
	0x65, 0x6d, 0x62, 0x65, 0x72, 0x49, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09,
	0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x49, 0x64, 0x73, 0x22, 0x47, 0x0a, 0x13, 0x43, 0x68, 0x72,
	0x6d, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x45, 0x78, 0x69, 0x73, 0x74, 0x49, 0x74, 0x65, 0x6d,
	0x12, 0x1a, 0x0a, 0x08, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05,
	0x65, 0x78, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x65, 0x78, 0x69,
	0x73, 0x74, 0x22, 0x42, 0x0a, 0x14, 0x43, 0x68, 0x72, 0x6d, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72,
	0x73, 0x45, 0x78, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x2a, 0x0a, 0x05, 0x69, 0x74,
	0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x43, 0x68, 0x72, 0x6d,
	0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x45, 0x78, 0x69, 0x73, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x52,
	0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x2a, 0x3a, 0x0a, 0x0d, 0x43, 0x68, 0x72, 0x6d, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x4a, 0x6f, 0x69, 0x6e, 0x10,
	0x00, 0x12, 0x08, 0x0a, 0x04, 0x51, 0x75, 0x69, 0x74, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x4b,
	0x69, 0x63, 0x6b, 0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07, 0x46, 0x61, 0x6c, 0x6c, 0x6f, 0x75, 0x74,
	0x10, 0x03, 0x2a, 0x3b, 0x0a, 0x10, 0x43, 0x68, 0x72, 0x6d, 0x44, 0x69, 0x73, 0x70, 0x61, 0x74,
	0x63, 0x68, 0x54, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x0e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x43, 0x68, 0x61, 0x74, 0x72, 0x6f, 0x6f, 0x6d, 0x10, 0x00, 0x12, 0x13, 0x0a, 0x0f, 0x44, 0x65,
	0x73, 0x74, 0x72, 0x6f, 0x79, 0x43, 0x68, 0x61, 0x74, 0x72, 0x6f, 0x6f, 0x6d, 0x10, 0x01, 0x2a,
	0x52, 0x0a, 0x17, 0x43, 0x68, 0x61, 0x74, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x44, 0x69,
	0x73, 0x70, 0x61, 0x74, 0x63, 0x68, 0x54, 0x79, 0x70, 0x65, 0x12, 0x13, 0x0a, 0x0f, 0x44, 0x69,
	0x73, 0x70, 0x61, 0x74, 0x63, 0x68, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x10, 0x00, 0x12,
	0x10, 0x0a, 0x0c, 0x4a, 0x6f, 0x69, 0x6e, 0x43, 0x68, 0x61, 0x74, 0x72, 0x6f, 0x6f, 0x6d, 0x10,
	0x01, 0x12, 0x10, 0x0a, 0x0c, 0x51, 0x75, 0x69, 0x74, 0x43, 0x68, 0x61, 0x74, 0x72, 0x6f, 0x6f,
	0x6d, 0x10, 0x02, 0x2a, 0x50, 0x0a, 0x0e, 0x43, 0x68, 0x61, 0x74, 0x41, 0x74, 0x74, 0x4f, 0x70,
	0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x12, 0x43, 0x68, 0x61, 0x74, 0x41, 0x74, 0x74,
	0x4f, 0x70, 0x74, 0x5f, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x10, 0x00, 0x12, 0x12, 0x0a,
	0x0e, 0x43, 0x68, 0x61, 0x74, 0x41, 0x74, 0x74, 0x4f, 0x70, 0x74, 0x5f, 0x41, 0x64, 0x64, 0x10,
	0x01, 0x12, 0x12, 0x0a, 0x0e, 0x43, 0x68, 0x61, 0x74, 0x41, 0x74, 0x74, 0x4f, 0x70, 0x74, 0x5f,
	0x44, 0x65, 0x6c, 0x10, 0x02, 0x2a, 0x44, 0x0a, 0x0b, 0x43, 0x68, 0x72, 0x6d, 0x42, 0x61, 0x6e,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x17, 0x0a, 0x13, 0x43, 0x68, 0x72, 0x6d, 0x42, 0x61, 0x6e, 0x54,
	0x79, 0x70, 0x65, 0x5f, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x10, 0x00, 0x12, 0x07, 0x0a,
	0x03, 0x42, 0x61, 0x6e, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x4d, 0x75, 0x74, 0x65, 0x10, 0x02,
	0x12, 0x09, 0x0a, 0x05, 0x41, 0x6c, 0x6c, 0x6f, 0x77, 0x10, 0x03, 0x42, 0x1f, 0x5a, 0x1d, 0x69,
	0x6d, 0x62, 0x6f, 0x74, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x73, 0x2f, 0x70, 0x62, 0x64, 0x65,
	0x66, 0x69, 0x6e, 0x65, 0x73, 0x2f, 0x70, 0x62, 0x6f, 0x62, 0x6a, 0x73, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_imbotclients_pbdefines_chatroom_proto_rawDescOnce sync.Once
	file_imbotclients_pbdefines_chatroom_proto_rawDescData = file_imbotclients_pbdefines_chatroom_proto_rawDesc
)

func file_imbotclients_pbdefines_chatroom_proto_rawDescGZIP() []byte {
	file_imbotclients_pbdefines_chatroom_proto_rawDescOnce.Do(func() {
		file_imbotclients_pbdefines_chatroom_proto_rawDescData = protoimpl.X.CompressGZIP(file_imbotclients_pbdefines_chatroom_proto_rawDescData)
	})
	return file_imbotclients_pbdefines_chatroom_proto_rawDescData
}

var file_imbotclients_pbdefines_chatroom_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_imbotclients_pbdefines_chatroom_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_imbotclients_pbdefines_chatroom_proto_goTypes = []interface{}{
	(ChrmEventType)(0),             // 0: ChrmEventType
	(ChrmDispatchType)(0),          // 1: ChrmDispatchType
	(ChatMembersDispatchType)(0),   // 2: ChatMembersDispatchType
	(ChatAttOptType)(0),            // 3: ChatAttOptType
	(ChrmBanType)(0),               // 4: ChrmBanType
	(*SyncChatroomReq)(nil),        // 5: SyncChatroomReq
	(*SyncChatroomMsgResp)(nil),    // 6: SyncChatroomMsgResp
	(*SyncChatroomAttResp)(nil),    // 7: SyncChatroomAttResp
	(*SyncChatroomEventResp)(nil),  // 8: SyncChatroomEventResp
	(*ChatroomEvents)(nil),         // 9: ChatroomEvents
	(*ChrmEvent)(nil),              // 10: ChrmEvent
	(*QryChatroomReq)(nil),         // 11: QryChatroomReq
	(*ChatroomReq)(nil),            // 12: ChatroomReq
	(*ChatroomInfo)(nil),           // 13: ChatroomInfo
	(*ChatMsgNode)(nil),            // 14: ChatMsgNode
	(*ChatroomMember)(nil),         // 15: ChatroomMember
	(*ChrmDispatchReq)(nil),        // 16: ChrmDispatchReq
	(*ChatMembersDispatchReq)(nil), // 17: ChatMembersDispatchReq
	(*ChatAttReq)(nil),             // 18: ChatAttReq
	(*ChatAttResp)(nil),            // 19: ChatAttResp
	(*ChatAttBatchReq)(nil),        // 20: ChatAttBatchReq
	(*ChatAttBatchResp)(nil),       // 21: ChatAttBatchResp
	(*ChatAttItem)(nil),            // 22: ChatAttItem
	(*ChatAtts)(nil),               // 23: ChatAtts
	(*BatchBanUserReq)(nil),        // 24: BatchBanUserReq
	(*QryChrmBanUsersReq)(nil),     // 25: QryChrmBanUsersReq
	(*QryChrmBanUsersResp)(nil),    // 26: QryChrmBanUsersResp
	(*ChrmBanMember)(nil),          // 27: ChrmBanMember
	(*ChrmMemberIds)(nil),          // 28: ChrmMemberIds
	(*ChrmMemberExistItem)(nil),    // 29: ChrmMemberExistItem
	(*ChrmMembersExistResp)(nil),   // 30: ChrmMembersExistResp
	(*DownMsg)(nil),                // 31: DownMsg
	(*UpMsg)(nil),                  // 32: UpMsg
}
var file_imbotclients_pbdefines_chatroom_proto_depIdxs = []int32{
	31, // 0: SyncChatroomMsgResp.msgs:type_name -> DownMsg
	22, // 1: SyncChatroomAttResp.atts:type_name -> ChatAttItem
	10, // 2: SyncChatroomEventResp.chrmEvents:type_name -> ChrmEvent
	10, // 3: ChatroomEvents.events:type_name -> ChrmEvent
	0,  // 4: ChrmEvent.eventType:type_name -> ChrmEventType
	15, // 5: ChatroomInfo.members:type_name -> ChatroomMember
	22, // 6: ChatroomInfo.atts:type_name -> ChatAttItem
	1,  // 7: ChrmDispatchReq.dispatchType:type_name -> ChrmDispatchType
	2,  // 8: ChatMembersDispatchReq.dispatchType:type_name -> ChatMembersDispatchType
	32, // 9: ChatAttReq.msg:type_name -> UpMsg
	18, // 10: ChatAttBatchReq.atts:type_name -> ChatAttReq
	19, // 11: ChatAttBatchResp.attResps:type_name -> ChatAttResp
	3,  // 12: ChatAttItem.optType:type_name -> ChatAttOptType
	22, // 13: ChatAtts.atts:type_name -> ChatAttItem
	4,  // 14: BatchBanUserReq.banType:type_name -> ChrmBanType
	4,  // 15: QryChrmBanUsersReq.banType:type_name -> ChrmBanType
	4,  // 16: QryChrmBanUsersResp.BanType:type_name -> ChrmBanType
	27, // 17: QryChrmBanUsersResp.members:type_name -> ChrmBanMember
	29, // 18: ChrmMembersExistResp.items:type_name -> ChrmMemberExistItem
	19, // [19:19] is the sub-list for method output_type
	19, // [19:19] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_imbotclients_pbdefines_chatroom_proto_init() }
func file_imbotclients_pbdefines_chatroom_proto_init() {
	if File_imbotclients_pbdefines_chatroom_proto != nil {
		return
	}
	file_imbotclients_pbdefines_appmessages_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_imbotclients_pbdefines_chatroom_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncChatroomReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_imbotclients_pbdefines_chatroom_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncChatroomMsgResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_imbotclients_pbdefines_chatroom_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncChatroomAttResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_imbotclients_pbdefines_chatroom_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncChatroomEventResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_imbotclients_pbdefines_chatroom_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatroomEvents); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_imbotclients_pbdefines_chatroom_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChrmEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_imbotclients_pbdefines_chatroom_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QryChatroomReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_imbotclients_pbdefines_chatroom_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatroomReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_imbotclients_pbdefines_chatroom_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatroomInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_imbotclients_pbdefines_chatroom_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatMsgNode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_imbotclients_pbdefines_chatroom_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatroomMember); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_imbotclients_pbdefines_chatroom_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChrmDispatchReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_imbotclients_pbdefines_chatroom_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatMembersDispatchReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_imbotclients_pbdefines_chatroom_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatAttReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_imbotclients_pbdefines_chatroom_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatAttResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_imbotclients_pbdefines_chatroom_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatAttBatchReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_imbotclients_pbdefines_chatroom_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatAttBatchResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_imbotclients_pbdefines_chatroom_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatAttItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_imbotclients_pbdefines_chatroom_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatAtts); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_imbotclients_pbdefines_chatroom_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BatchBanUserReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_imbotclients_pbdefines_chatroom_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QryChrmBanUsersReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_imbotclients_pbdefines_chatroom_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QryChrmBanUsersResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_imbotclients_pbdefines_chatroom_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChrmBanMember); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_imbotclients_pbdefines_chatroom_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChrmMemberIds); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_imbotclients_pbdefines_chatroom_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChrmMemberExistItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_imbotclients_pbdefines_chatroom_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChrmMembersExistResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_imbotclients_pbdefines_chatroom_proto_rawDesc,
			NumEnums:      5,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_imbotclients_pbdefines_chatroom_proto_goTypes,
		DependencyIndexes: file_imbotclients_pbdefines_chatroom_proto_depIdxs,
		EnumInfos:         file_imbotclients_pbdefines_chatroom_proto_enumTypes,
		MessageInfos:      file_imbotclients_pbdefines_chatroom_proto_msgTypes,
	}.Build()
	File_imbotclients_pbdefines_chatroom_proto = out.File
	file_imbotclients_pbdefines_chatroom_proto_rawDesc = nil
	file_imbotclients_pbdefines_chatroom_proto_goTypes = nil
	file_imbotclients_pbdefines_chatroom_proto_depIdxs = nil
}
